[package]
name = "tpi"
version = "1.0.5"
edition = "2021"
license = "Apache-2.0"
authors = ["Sven Rademakers <sven@turingpi.com>", "Ruslan Akbashev <ra@turingpi.com>"]
description = "Official Turing-Pi2 CLI tool"
homepage = "https://turingpi.com/"
repository = "https://github.com/turing-machines/tpi"
readme = "README.md"
categories= ["command-line-interface"]
keywords= ["turing-pi", "tpi", "CLI", "edge-computing", "board-management"]
exclude = [".github", "deny.toml", "scripts/ci/*"]

[dependencies]
anyhow = "1.0.86"
aw-fel = "0.5.2"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive", "wrap_help", "env"] }
clap_complete = "4.5.2"
crossterm = "=0.24.0"
dirs = "5.0.1"
indicatif = { version = "0.17.8", features = ["tokio"] }
platform-info = "2.0.3"
reqwest = { version = "0.12.4", default-features = false, features = ["gzip", "json", "multipart", "stream"] }
rusb = "0.9.4"
serde_json = "1.0.117"
tar = "0.4.40"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
tokio-util = "0.7.11"
url = "2.5.0"

[features]
default = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
localhost = []

[patch.crates-io]
aw-fel = { path = "/home/svenr/aw-fel-rs", version="*" }
