[package]
name = "tpi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
description = "CLI tool to control a Turing-Pi board"
homepage = "https://turingpi.com/"
repository = "https://github.com/turing-machines/tpi"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
clap_complete = "4.3.2"
log = "0.4.19"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls-native-roots", "json", "multipart"] }
serde_json = "1.0.104"
simple_logger = { version = "4.2.0", default-features = false, features = ["colors"] }
tokio = { version = "1.29.1", features = ["rt", "rt-multi-thread", "macros", "fs"] }
url = "2.4.0"

